version: "3.8"
services:
  wg-easy:
    environment:
      - WG_HOST
      - PASSWORD
      - WG_PORT
      - WG_DEFAULT_ADDRESS
    image: weejewel/wg-easy
    container_name: wg-easy
    volumes:
      - .:/etc/wireguard
    networks:
      - wg-easy
    ports:
      - "51820:51820/udp"
      - "51821"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  https-portal:
    image: steveltn/https-portal:1
    depends_on:
      - wg-easy
    networks:
      - wg-easy
    ports:
      - '80:80'
      - '443:443'
    environment:
      DOMAINS: "$DOMAIN -> http://wg-easy:51821"
      STAGE: production
      PROXY_READ_TIMEOUT: 3600
      CLIENT_MAX_BODY_SIZE: 100M
    volumes:
      - ssl-certs:/var/lib/https-portal

networks:
  wg-easy:
    driver: bridge

volumes:
  ssl-certs: {}
